//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siscob
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContratoContext : DbContext
    {
        public ContratoContext()
            : base("name=ContratoContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Contrato> ContratoSet { get; set; }
        public DbSet<Empresa> EmpresaSet { get; set; }
        public DbSet<Documento> DocumentoSet { get; set; }
        public DbSet<Funcionario> FuncionarioSet { get; set; }
        public DbSet<Pagamento> PagamentoSet { get; set; }
        public DbSet<Cliente> ClienteSet { get; set; }
    }
}
