//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siscob
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagamento
    {
        public int IdPagamento { get; set; }
        public double ValorIntegralDaParcela { get; set; }
        public double ValorEmAberto { get; set; }
        public int ContratoIdContrato { get; set; }
        public int ClienteIdCliente { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
